# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: DBTest

on:
  push:
    branches: [ "master" ]
    paths:
      - 'database/**.go'

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: 123456
    steps:
    - name: Git checkout
    - uses: actions/checkout@v3

    - name: Start MySQL
      run : |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./database
