# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: DBTest

on:
  push:
    branches: [ "master" ]
    paths:
      - 'database/**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:7.0
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: go test -v ./database
